name: github_dev_search
description: Search devs in GitHub by location.
version: 0.0.1
homepage: https://github.com/webdeploy-bologni-federico/github-dev-search

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.10.0
dependencies: 
  args: ^2.1.0
  http: ^0.13.3
